name: Daily Sync

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um 0:00 UTC (das entspricht 2:00 Uhr MEZ+2)
  workflow_dispatch: # Ermöglicht manuelle Ausführung

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl schedule google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client python-dotenv img2pdf
      continue-on-error: false # Beendet den Workflow, wenn die Installation fehlschlägt

    - name: Set up environment variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
      continue-on-error: false # Beendet den Workflow, wenn die Umgebungsvariablen nicht gesetzt werden können

    - name: Create exports directory
      run: |
        mkdir -p exports

    - name: Run sync_purchases.py
      run: python sync_purchases.py
      continue-on-error: false # Beendet den Workflow, wenn das Skript fehlschlägt

    - name: Run sync_expenses.py
      run: python sync_expenses.py
      continue-on-error: false # Beendet den Workflow, wenn das Skript fehlschlägt

    - name: Run sync_campaigns.py
      run: python sync_campaigns.py
      continue-on-error: false # Beendet den Workflow, wenn das Skript fehlschlägt
